### ISSUE TITLE
Line 250 in MultiTenancy has incorrect signature

### ISSUE THREAD

**Issue by glaidler** [ServiceStack/docs#16]
```
OrmLiteAuthRepositoryMultTenancy(container.TryResolve<IDbConnectionFactory>())
```
won't work as it's expecting a 2nd parameter which is an array of strings.  Not sure whether passing null or empty string to this method breaks things so would be great if this was detailed in this example.

**Comment by mythz** [comment]
I've just [added params to make it optional](https://github.com/ServiceStack/ServiceStack/commit/79c08feab8c1927afb6cb5b3439f7ad90eb9f782), this is used to create the schemas of the Auth tables used, you can pass an empty `string[0]` if you're creating the schemas out of band.
