### ISSUE TITLE
Need to use BearerToken not Credentials with an ApiKey

### ISSUE THREAD

**Issue by CampsiteHelper** [ServiceStack/docs#43]
`var client = new JsonServiceClient(baseUrl) {
    Credentials = new NetworkCredential(apiKey, "") // this one doesn't work anymore
};

var client = new JsonHttpClient(baseUrl) {
    BearerToken = apiKey  // this works
};`

**Comment by mythz** [comment]
We have several tests in [ApiKeyAuthTests.cs](https://github.com/ServiceStack/ServiceStack/blob/master/tests/ServiceStack.Server.Tests/Auth/ApiKeyAuthTests.cs) showing it still does.

If you provide a stand-alone repro with full error details I can look into what's not working for you.
