### ISSUE TITLE
Paid but Free: marketplace image shows 'paid' - needs replacing

### ISSUE THREAD

**Issue by OzBob** [ServiceStack/docs#49]
Hi guys, I would have put a PR in myself but the asset:
https://raw.githubusercontent.com/ServiceStack/Assets/master/img/servicestackvs/vsgallery-download.png
Doesn't seem to be in a GitHub repo I can find.

I did a search for occurrences:
https://github.com/search?p=2&q=vsgallery-download.png&type=Code

I though this one would be more encouraging, I had to double check, when I say "paid".

BTW - thanks for making it free. Keep up the good work.

![image](https://user-images.githubusercontent.com/1796771/63416534-26361c00-c432-11e9-92ea-4155b2c0cb3d.png)

**Comment by mythz** [comment]
Cheers, added in [this commit](https://github.com/ServiceStack/Assets/commit/f90243d42b1acb09e1357a4e6c8dcbbd18990167),

thx for the PR!
