### ISSUE TITLE
RouteSummary property in OpenApiFeature does not exist

### ISSUE THREAD

**Issue by nad-au** [ServiceStack/docs#52]
The Open API docs states:
The Swagger UI groups multiple routes under a single top-level route that covers multiple different services sharing the top-level route which can be specified using the RouteSummary dictionary of the OpenApiFeature plugin, e.g:
```csharp
Plugins.Add(new OpenApiFeature {
    RouteSummary = {
        { "/top-level-path", "Route Summary" }
    }
});
```
but RouteSummary isn't available, at least not in ServiceStack.Api.OpenApi v5.7.0

**Comment by mythz** [comment]
Thx, this was only available in the old Swagger API Feature, removed in https://github.com/ServiceStack/docs/commit/ef0605f4b8a505bc54bc4352a6776f799fbb2dfa
