### ISSUE TITLE
TypeScript version update in docs

### ISSUE THREAD

**Issue by nad-au** [ServiceStack/docs#53]
https://docs.servicestack.net/typescript-add-servicestack-reference

"We’re actively tracking TypeScript’s evolution and looking forward to integrating TypeScript 2.0 once it leaves beta."

Given 3.6 was released recently, perhaps this paragraph should be removed.

**Comment by mythz** [comment]
Removed, Cheers 👍 
https://github.com/ServiceStack/docs/commit/4df720b2bb09ed7278cc516ac05a2a971e4a9451
