### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by stefandevo** [ServiceStack/docs#57]
Just to let you know:
http://razor.servicestack.net/
is linked under View Engines, but it does not work anymore.

**Comment by mythz** [comment]
thx, I've changed it to redirect to http://razor.netcore.io

**Comment by mythz** [comment]
Actually these aren't one of the netcore.io redirects, seems that the proxied Win VM ran out of disk space, cleared logs and iisreset and we're good to go.
