### ISSUE TITLE
appsettings.json license option does not appear to work

### ISSUE THREAD

**Issue by whighsmith** [ServiceStack/docs#83]
Continue to get the license error even when license is applied to the appsettings.json file: 

ServiceStack.LicenseException: The free-quota limit on '6000 Redis requests per hour' has been reached.

- [ ] OS : Windows 10 Enterprise
- [ ] Visual Studio Version : Microsoft Visual Studio Professional 2019 Version 16.11.1
- [ ] Target Framework :  .Net 5.0
- [ ] ServiceStack.Redis.DLL File Version : 5.12.0.0
- [ ] appsettings.json file encoding: "Western European (Windows) - Codepage 1252"
- [ ] The Sourcecode option **does** work: Licensing.RegisterLicense("18242-e1JlZ...==");

-----------------------------------------------------
```
{
    "servicestack": {
        "license": "{18242-A1JIZ.....==}"
    }
}
```
-----------------------------------------------------
**This option should work, but does not:**
```
{
    "servicestack": {
        "license": "18242-A1JIZ.....=="
    }
}
```
-----------------------------------------------------
```
{
    "servicestack": {
        "license": "{A1JIZ.....==}"
    }
}
```
-----------------------------------------------------
```
{
    "servicestack": {
        "license": "A1JIZ.....=="
    }
}
```

**Comment by mythz** [comment]
Yeah that's only if you use https://servicestack.net is the ServiceStack AppHost able to auto register the license key from the configured `IConfiguration` provider, if you're just using Redis client on its own you can register it with:

```csharp
Licensing.RegisterLicense(Configuration.GetValue<string>("servicestack:license"))
```

Please note our issue tracker is located at: https://github.com/ServiceStack/Issues
