### ISSUE TITLE
Cancellable request doc seems to be wrong

### ISSUE THREAD

**Issue by mohan-murali** [ServiceStack/docs#84]
Hi,

I don't think the docs for cancellable request of service stack is correct. I am trying to implement the same and I am finding things missing.

Link - https://docs.servicestack.net/cancellable-requests

So the issues I found are 
-  Guid generation method is not correct. If I copy the below code into doc, I get error
```jsx
var tag = Guid.NewGuid().ToString();
```
- JsonServiceClient does not seem have a method that exposes the request object, to set the Xtag in header. 

Kindly look through the docs. Thanks

**Comment by mythz** [comment]
The docs are accurate, as the code example compiles without issue:

```csharp
var baseUri = "https://example.org";
var tag = Guid.NewGuid().ToString();
var client = new JsonServiceClient(baseUri) {
    RequestFilter = req => req.Headers[HttpHeaders.XTag] = tag
};
```

Your project must have issues, `Guid.NewGuid()` is a core Type built into the .NET BCL.
